sudo: requiered
services:
    - docker


before_install:
    - docker build -t kotanya/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true kotanya/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-096188985014"
    bucket_path: "docker-react"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
